# -*- coding: utf-8 -*-
"""Heart-disease.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sSRTC5HAvVlLdO6grD5oRcksatTnsxGz

Importing required libraries
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""Importing Dataset"""

from google.colab import files
uploaded = files.upload()
d = pd.read_csv(list(uploaded.keys())[0])

d.head()

"""**EDA**"""

sns.countplot(x='target',data=d,palette='bwr',
color='red')

sns.countplot(x='target',hue='sex',data=d,palette='bwr',
color='red')

bins=[29,40,50,60,70,80]
lables=["30-39","40-49","50-59","60-69","70-79"]
d["age_group"]=pd.cut(d['age'],bins=bins,labels=lables)
sns.countplot(x='age_group',hue='target',data=d,palette='bwr',
color='red')

#divide into x and y
x=d.drop("target",axis=1)
y=d["target"]

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=55)

from sklearn.metrics import accuracy_score, log_loss,confusion_matrix
acc=accuracy_score(y_test,y_predict)
loss=log_loss(y_test,y_predict)
conf=confusion_matrix(y_test,y_predict)
print(conf)
print(loss)
print(acc)

from sklearn.linear_model import LogisticRegression
model = LogisticRegression(solver='liblinear', random_state=42)
model.fit(x_train, y_train)
y_predict = model.predict(x_test)

#save the final model
import joblib
joblib.dump(model,'logistic_regression_model.pkl')
print("Model saved successfully.")



"""# Task
Save the trained logistic regression model.

## Fix `NameError`

### Subtask:
Replace `train_model` with `model` in the `joblib.dump()` function to correctly save the trained logistic regression model.

## Summary:

### Data Analysis Key Findings
*   An error (`NameError`) was encountered when attempting to save the trained logistic regression model using `joblib.dump()`.
*   The error was specifically due to referencing an undefined variable named `train_model` instead of the correctly defined variable `model` which holds the trained logistic regression object.

### Insights or Next Steps
*   The corrected code will now successfully save the trained logistic regression `model` object to a file, allowing for its persistence and subsequent loading for inference or further analysis.
*   It is crucial to verify variable names and their scope during development to prevent `NameError` and ensure smooth execution of operations like model serialization.
"""